# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12Lhi7t21O5zFqtktUuYNcUStdsjBqomr

# 在 Google Colab 中完成一个图像分类模型的训练和导出

通过自定义虚拟环境的方式切换到兼容的 Python 3.9，并安装一系列精确版本的依赖。

### 新段落
"""

# 安装 python3.9 及必要工具
!sudo apt-get update -y
!sudo apt-get install python3.9 python3.9-venv python3.9-distutils curl -y
# 创建虚拟环境（不会自带 pip）
!python3.9 -m venv /content/tflite_env
# 下载官方 get-pip 脚本
!curl -sS https://bootstrap.pypa.io/get-pip.py -o get-pip.py

# 使用虚拟环境中的 python 执行脚本安装 pip
!/content/tflite_env/bin/python get-pip.py
#验证 pip 是否生效
!/content/tflite_env/bin/pip --version

"""安装核心依赖"""

! /content/tflite_env/bin/pip install -q \
  tensorflow==2.10.0 \
  keras==2.10.0 \
  numpy==1.23.5 \
  protobuf==3.19.6 \
  tensorflow-hub==0.12.0 \
  tflite-support==0.4.2 \
  tensorflow-datasets==4.8.3 \
  sentencepiece==0.1.99 \
  sounddevice==0.4.5 \
  librosa==0.8.1 \
  flatbuffers==23.5.26 \
  matplotlib==3.5.3 \
  opencv-python==4.8.0.76

"""安装 tflite-model-maker 本体"""

! /content/tflite_env/bin/pip install tflite-model-maker==0.4.2

"""补充缺失依赖"""

! /content/tflite_env/bin/pip install matplotlib_inline IPython

"""验证是否成功安装"""

! /content/tflite_env/bin/python -c "from tflite_model_maker import image_classifier; print('TFLite Model Maker 已成功导入')"

"""训练模型（花卉分类）"""

# step_train.py
with open('/content/step_train.py', 'w') as f:
    f.write("""
import tensorflow as tf
from tflite_model_maker import image_classifier
from tflite_model_maker.image_classifier import DataLoader

image_path = tf.keras.utils.get_file(
    'flower_photos',
    'https://storage.googleapis.com/download.tensorflow.org/example_images/flower_photos.tgz',
    untar=True)

data = DataLoader.from_folder(image_path)
train_data, test_data = data.split(0.9)

model = image_classifier.create(train_data)
loss, acc = model.evaluate(test_data)
print(f'✅ 测试准确率: {acc:.4f}')
model.export(export_dir='.')
""")
! /content/tflite_env/bin/python /content/step_train.py

"""将训练好的tflite模型下载"""

from google.colab import files
files.download('model.tflite')

"""此次学习，让我掌握了在特定环境下解决依赖冲突的有效方法。TFLite Model Maker 版本与 TensorFlow、NumPy 等存在依赖冲突，且 Colab 默认 Python 版本不适配，这是学习过程中面临的主要难题。通过创建 Python 3.9 虚拟环境，并精确安装指定版本的依赖包，我成功克服了这些障碍。在这个过程中，我深入理解了 Python 虚拟环境的隔离作用，以及不同版本库之间相互配合的重要性，这对今后在复杂环境中部署项目具有重要的指导意义。​
实践过程中，我也体会到了在 Colab 环境中操作的独特性。由于 Colab 不支持传统的source激活虚拟环境方式，需要手动指定路径调用环境中的 Python 和 pip，这种特殊的操作方式让我意识到，在不同的平台和工具中，执行相同任务可能存在不同的实现方法，这要求我们保持灵活应变的思维，善于根据实际情况调整解决方案。​
从花卉分类模型的训练和导出流程来看，我对 TFLite Model Maker 的工作机制有了更直观的感受。通过一步步执行代码，从安装库到导入模块，再到训练模型、导出并下载，整个过程让我对机器学习模型从开发到部署的完整链路有了清晰的认知。这不仅增强了我的动手实践能力，也让我对机器学习应用有了更浓厚的兴趣。
"""